name: paralle_test_workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        default: 'bal-perf-cluster-test'
        required: false
      test-name:
        description: 'test name'
        default: 'test_passthrough'
        required: false
      sku:
        description: 'node VM size'
        default: 'Standard_F16s_v2'
        required: false
jobs:
  execute_test_1:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-1
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  # execute_test_2:
  #   uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
  #   with:
  #     clusterName: ${{ github.event.inputs.clusterName}}-2
  #   secrets:
  #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  #     AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
  #     AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
  #     CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
  #     DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #     DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  #     VM_USER: ${{ secrets.VM_USER }}
  
