name: paralle_test_workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        default: 'bal-perf-cluster-test'
        required: false
      test-name:
        description: 'test name'
        default: 'test_passthrough'
        required: false
      sku:
        description: 'node VM size'
        default: 'Standard_F16s_v2'
        required: false
jobs:
  execute_test_1:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-1
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_2:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-2
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_3:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-3
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_4:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-4
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_5:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-5
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_6:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-6
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_7:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-7
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_8:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-8
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_9:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-9
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
  execute_test_10:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-10
      test-name: ${{ github.event.inputs.test-name}}
      sku: ${{ github.event.inputs.sku}}
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_ID: ${{ secrets.AZURE_APP_ID }}
      AZURE_APP_PASSWORD: ${{ secrets.AZURE_APP_PASSWORD }}
      CLUSTER_RESOURCE_GROUP: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      VM_USER: ${{ secrets.VM_USER }}
