name: test_workflow

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Cluster name'
        default: 'bal-perf-cluster-test'
        required: false
jobs:
  execute_test_1:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-1
  execute_test_2:
    uses: DevOp-With-Github/platform-test/.github/workflows/test_workflow_reuse.yml@main
    with:
      clusterName: ${{ github.event.inputs.clusterName}}-2
  
